version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:13
    container_name: talentree-postgres
    environment:
      POSTGRES_DB: talentree_db
      POSTGRES_USER: talentree_user
      POSTGRES_PASSWORD: talentree_password
    ports:
      - '15432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis para cache
  redis:
    image: redis:7-alpine
    container_name: talentree-redis
    ports:
      - '16379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talentree-backend
    environment:
      # Database Configuration
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: talentree_user
      DB_PASSWORD: talentree_password
      DB_DATABASE: talentree_db
      DB_SYNCHRONIZE: 'true'
      DB_LOGGING: 'true'
      DB_DROP_SCHEMA: 'false'

      # JWT Configuration
      JWT_SECRET: talentree_jwt_secret_2024_very_secure_key
      JWT_EXPIRATION: 1d
      JWT_REFRESH_SECRET: talentree_refresh_secret_2024_very_secure_key
      JWT_REFRESH_EXPIRATION: 7d

      # Server Configuration
      PORT: 3000
      API_PREFIX: api/v1
      CORS_ORIGIN: http://localhost:5173

      # Cache Configuration
      CACHE_TTL_MS: 300000
      CACHE_MAX: 1000
    ports:
      - '3002:3000'
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
